/**
 * Locks in a Nav Grid Editor export as the new baked navigation map.
 *
 *   node scripts/lock-in-grid.mjs <export.json>
 *
 * The export JSON comes from the "Copy map" button in the Nav Grid Editor
 * (components/office/GridEditorPanel.tsx) and looks like:
 *
 *   { "grid": { "cols": 42, "rows": 42, "cellSize": 0.25 },
 *     "blocked": ["0,0", "0,1", ...],
 *     "source": "notelings-grid-editor" }
 *
 * Validates the export against the 42×42 @ 0.25 m grid, then regenerates
 * components/office/newOfficeGridData.ts (sorted blocked set + ASCII map) in
 * the same format the GLB generator emits. After locking in, update any
 * grid-invariant tests that the new map changes (e.g. specific pocket cells).
 */
import fs from 'node:fs'
import path from 'node:path'

const file = process.argv[2]
if (!file) {
  console.error('Usage: node scripts/lock-in-grid.mjs <export.json>')
  process.exit(1)
}

let data
try {
  data = JSON.parse(fs.readFileSync(file, 'utf8'))
} catch (error) {
  console.error('Could not read export:', error.message)
  process.exit(1)
}

const { grid, blocked } = data
const cols = grid?.cols
const rows = grid?.rows
const cell = grid?.cellSize
if (cols !== 42 || rows !== 42 || Math.abs((cell ?? 0) - 0.25) > 1e-9) {
  console.error(`Export must be the 42×42 @ 0.25 m grid (got ${cols}×${rows} @ ${cell})`)
  process.exit(1)
}
if (!Array.isArray(blocked) || blocked.length === 0) {
  console.error('Export has no blocked cells')
  process.exit(1)
}

const seen = new Set()
for (const key of blocked) {
  const [c, r] = key.split(',').map(Number)
  if (
    !Number.isInteger(c) || !Number.isInteger(r) ||
    c < 0 || c >= cols || r < 0 || r >= rows || seen.has(key)
  ) {
    console.error(`Invalid or duplicate blocked key: ${key}`)
    process.exit(1)
  }
  seen.add(key)
}

// --- Navigation invariants (mirror of the grid unit tests) ---
// Robot spawns + delivery staging cells (see agentDestinations/newOfficeGrid):
// blue [5,11], green [30,4], red [32,18]; whiteboard [22,37], printer [34,4],
// corkboard [3,21], trash [27,8]. Locking in a map that blocks or strands any
// of them would break the app, so the lock-in is REJECTED instead.
const REQUIRED_FREE = [
  [5, 11], [30, 4], [32, 18],
  [22, 37], [34, 4], [3, 21], [27, 8],
]
const missing = REQUIRED_FREE.filter(([c, r]) => seen.has(`${c},${r}`))
if (missing.length > 0) {
  console.error(`Lock-in REJECTED: required walkable cells are blocked: ${missing.map(([c, r]) => `(${c},${r})`).join(', ')}`)
  process.exit(1)
}

// Connectivity: 4-dir flood fill over the free cells from the blue start;
// every required cell must be reachable (this would have caught the
// 2026-08-11 whole-mesh AABB experiment that disconnected the Work route).
const free = new Set()
for (let r = 0; r < rows; r += 1) {
  for (let c = 0; c < cols; c += 1) {
    if (!seen.has(`${c},${r}`)) free.add(`${c},${r}`)
  }
}
const queue = ['5,11']
const visited = new Set(queue)
while (queue.length > 0) {
  const [c, r] = queue.pop().split(',').map(Number)
  for (const [dc, dr] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
    const key = `${c + dc},${r + dr}`
    if (free.has(key) && !visited.has(key)) {
      visited.add(key)
      queue.push(key)
    }
  }
}
const unreachable = REQUIRED_FREE.filter(([c, r]) => !visited.has(`${c},${r}`))
if (unreachable.length > 0) {
  console.error(`Lock-in REJECTED: unreachable walkable cells: ${unreachable.map(([c, r]) => `(${c},${r})`).join(', ')}`)
  process.exit(1)
}

const sorted = [...blocked].sort((a, b) => {
  const [ca, ra] = a.split(',').map(Number)
  const [cb, rb] = b.split(',').map(Number)
  return ra - rb || ca - cb
})

// ASCII map: first line = row 41 (back, z≈5.0), last = row 0 (front, z≈-5.25).
const ascii = []
for (let r = rows - 1; r >= 0; r -= 1) {
  let line = ''
  for (let c = 0; c < cols; c += 1) line += seen.has(`${c},${r}`) ? '#' : '.'
  ascii.push(line)
}

const blockedLines = []
for (let i = 0; i < sorted.length; i += 12) {
  blockedLines.push('  ' + sorted.slice(i, i + 12).map((k) => `'${k}'`).join(', '))
}

const output = `// GENERATED by scripts/generate-new-office-grid.mjs or scripts/lock-in-grid.mjs — do not edit by hand.
// Regenerate after any change to public/models/3D_Note_Office_2/3d_note_office.glb:
//   node scripts/generate-new-office-grid.mjs
// (or lock in a manual Nav Grid Editor export with scripts/lock-in-grid.mjs)
/**
 * Blocked cells for the 3D Note Office (42×42 @ 0.25 m, world origin (0,0)).
 * This map was locked in from the manual Nav Grid Editor export (2026-08-12):
 * the baked GLB rasterization plus the user's hand-painted walkable-area edits.
 * Keys are "col,row": row 41 = back (z≈5.0), row 0 = front (z≈-5.25);
 * col 0 = left (x≈-5.25).
 */
export const NEW_OFFICE_BLOCKED_CELLS: ReadonlySet<string> = new Set([
${blockedLines.join(',\n')},
])

/** ASCII visualization of the final blocked map (# blocked, . free). */
export const NEW_OFFICE_ASCII_MAP: readonly string[] = [
${ascii.map((line) => `  '${line}'`).join(',\n')},
]
`

const outPath = path.resolve('components/office/newOfficeGridData.ts')
fs.writeFileSync(outPath, output)
console.log(`Wrote ${outPath} (${sorted.length} blocked cells, ${ascii.length} map rows)`)
